import Head from 'next/head'
import Image from 'next/image'

import Header from './Components/Header'
import TopCards from '@/Components/TopCards'
import BarChart from '@/Components/BarChart'
import RecentOrder from '@/Components/RecentOrder'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header/>
        <TopCards/>
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
           <BarChart/>
           <RecentOrder/>
        </div>
      </main>
    </>
  )
}
